#!/usr/bin/env python3
"""
Creative Writing Project Setup

Creates a new project directory with the expected structure,
symlinks CLAUDE.md to parent, and updates config.yaml.
"""

import argparse
import os
import sys
from pathlib import Path

TOOLKIT_DIR = Path(__file__).parent.resolve()

DIRECTORIES = [
    "stories",
    "worldbuilding",
    "documents",
    "notes",
]

GITIGNORE_CONTENT = """\
# Vector database (regenerated by toolkit)
vector_db/

# Python cache
__pycache__/
*.pyc

# Editor files
*~
.DS_Store
*.swp
"""


def update_config(project_name: str):
    """Update config.yaml to point at the new project."""
    config_path = TOOLKIT_DIR / "config.yaml"

    new_content = f"""\
# Fairy Toolkit Configuration
#
# Point this at your content directory (stories, worldbuilding, etc.)
# Path is relative to this config file's location.

content_root: ../{project_name}
"""
    config_path.write_text(new_content)


def main():
    parser = argparse.ArgumentParser(
        description="Set up a new creative writing project"
    )
    parser.add_argument(
        "--dirname", "-d",
        default="../my-project",
        help="Directory to create (default: ../my-project)"
    )
    args = parser.parse_args()

    target = Path(args.dirname)

    # Resolve relative to toolkit directory
    if not target.is_absolute():
        target = (TOOLKIT_DIR / target).resolve()

    parent_dir = target.parent
    project_name = target.name
    claude_link = parent_dir / "CLAUDE.md"
    claude_source = TOOLKIT_DIR / "CLAUDE.md"

    print()
    print("=" * 60)
    print("Creative Writing Toolkit - Project Setup")
    print("=" * 60)
    print()
    print("This will:")
    print(f"  1. Create project directory: {target}/")
    for d in DIRECTORIES:
        print(f"       └── {d}/")
    print(f"  2. Create .gitignore in project")
    print(f"  3. Symlink CLAUDE.md to parent: {claude_link}")
    print(f"  4. Update config.yaml to point at: ../{project_name}")
    print()

    if target.exists() and any(target.iterdir()):
        print(f"WARNING: {target}/ exists and is not empty!")
        print()

    if claude_link.exists() or claude_link.is_symlink():
        print(f"NOTE: {claude_link} already exists (will skip symlink)")
        print()

    print("Are you sure you want to proceed?")
    response = input('Type "YES" to continue: ')
    if response != "YES":
        print("Aborted.")
        sys.exit(1)
    print()

    # Create project directory
    target.mkdir(parents=True, exist_ok=True)
    print(f"Created {target}/")

    # Create subdirectories
    for d in DIRECTORIES:
        (target / d).mkdir(exist_ok=True)
        print(f"Created {target}/{d}/")

    # Create .gitignore
    gitignore_path = target / ".gitignore"
    if not gitignore_path.exists():
        gitignore_path.write_text(GITIGNORE_CONTENT)
        print(f"Created {gitignore_path}")
    else:
        print(f"Skipped .gitignore (already exists)")

    # Symlink CLAUDE.md to parent
    if not claude_link.exists() and not claude_link.is_symlink():
        rel_path = os.path.relpath(claude_source, parent_dir)
        claude_link.symlink_to(rel_path)
        print(f"Linked {claude_link} -> {rel_path}")
    else:
        print(f"Skipped CLAUDE.md symlink (already exists)")

    # Update config.yaml
    update_config(project_name)
    print(f"Updated config.yaml: content_root: ../{project_name}")

    print()
    print("=" * 60)
    print("Setup complete!")
    print("=" * 60)
    print()
    print("Next steps:")
    print()
    print(f"  1. cd {parent_dir}")
    print(f"  2. Add content to {project_name}/stories/, {project_name}/worldbuilding/, etc.")
    print(f"  3. Index: ./fairy-toolkit/index.py --rebuild")
    print(f"  4. Search: ./fairy-toolkit/search.py 'your query'")
    print()
    print("To use with Claude Code:")
    print()
    print(f"  cd {parent_dir}")
    print("  claude")
    print()
    print("(Always run Claude from the parent directory!)")
    print()


if __name__ == "__main__":
    main()
